apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat 
  namespace: infranics
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32161 
    name: http
  - port: 8443 
    protocol: TCP
    targetPort: 8443 
    nodePort: 32543
    name: https
  selector:
    app: tomcat 
  type: NodePort
